### ISSUE TITLE
Code access

### ISSUE THREAD

**Issue by alxmjo** [orhan/trafico#1]
Out of curiosity, why is code access permission necessary? I'd like to use this for a project but this is holding me back. Thanks.

**Comment by orhan** [comment]
To be honest, I don't remember why! 😅

Maybe I added that because of a feature that I had in mind (before I kind of lost the purpose/interest in the project), so you can try without that permission, should actually work without it. 👍

**Comment by orhan** [comment]
Sorry for the unhelpful comment, I just remembered why it needs code access: 
Trafico needs to read the `.github/trafico.yml` to read the rules specified there (labels and colors to apply), that's why it needs "code access", but other than that, Trafico doesn't read any code, it just looks at metadata of PRs.

So it's pretty harmless. 👍

**Comment by alxmjo** [comment]
Ok. Good to know. Thanks!

**Comment by rohitjmathew** [comment]
> Sorry for the unhelpful comment, I just remembered why it needs code access:
> Trafico needs to read the `.github/trafico.yml` to read the rules specified there (labels and colors to apply), that's why it needs "code access", but other than that, Trafico doesn't read any code, it just looks at metadata of PRs.
> 
> So it's pretty harmless. 👍

@orhan just to clarify, is it not possible to use the following [permission](https://user-images.githubusercontent.com/17832347/95388251-968e4e00-090f-11eb-997e-6debbf24f707.png) to enable the same instead of having read access to code?

**Comment by orhan** [comment]
Oh wow, sorry for being so lazy guys, I didn't check it properly last time around.

Yes @rohitjmathew, you're right, it only needed the single file access.

I think I added the code access pro-actively, because I had features in mind that triggered different builds with certain commit messages and stuff like that, but never got to implement it. 

I updated the permissions now. 👍
